//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer17.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viewer17.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _404 {
            get {
                object obj = ResourceManager.GetObject("_404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_in {
            get {
                object obj = ResourceManager.GetObject("arrow_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap arrow_out {
            get {
                object obj = ResourceManager.GetObject("arrow_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   BG color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnBgColor {
            get {
                return ResourceManager.GetString("ColumnBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Button name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnButtonName {
            get {
                return ResourceManager.GetString("ColumnButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnDirName {
            get {
                return ResourceManager.GetString("ColumnDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FG color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnFgColor {
            get {
                return ResourceManager.GetString("ColumnFgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnIcon {
            get {
                return ResourceManager.GetString("ColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnId {
            get {
                return ResourceManager.GetString("ColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnKey {
            get {
                return ResourceManager.GetString("ColumnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnOpe {
            get {
                return ResourceManager.GetString("ColumnOpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Panel name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPanelName {
            get {
                return ResourceManager.GetString("ColumnPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnPos {
            get {
                return ResourceManager.GetString("ColumnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap layer_transparent {
            get {
                object obj = ResourceManager.GetObject("layer_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This is the first picture!\nUnlocked Act2.\nYou can change with the top right icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 17th picture!\nUnlocked button resizing.\nLet&apos;s make large buttons. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level17 {
            get {
                return ResourceManager.GetString("Level17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 170th picture!\nUnlocked the layout for left-handed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level170 {
            get {
                return ResourceManager.GetString("Level170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 1,700th picture!\nUnlocked go/back by 100 sheets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level1700 {
            get {
                return ResourceManager.GetString("Level1700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 17,000th picture!\nUnlocked go/back by 1000 sheets. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level17000 {
            get {
                return ResourceManager.GetString("Level17000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the 7th picture!\nUnlocked Act3.\nYou can change with the top right icon. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeCopy {
            get {
                return ResourceManager.GetString("OpeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeDelete {
            get {
                return ResourceManager.GetString("OpeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeMove {
            get {
                return ResourceManager.GetString("OpeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeUndo {
            get {
                return ResourceManager.GetString("OpeUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosBottomLeft {
            get {
                return ResourceManager.GetString("PosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosBottomRight {
            get {
                return ResourceManager.GetString("PosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosTopLeft {
            get {
                return ResourceManager.GetString("PosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PosTopRight {
            get {
                return ResourceManager.GetString("PosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Del に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
    }
}
